ITEMS_OF_INTEREST := {}
ITEMS_OF_INTEREST["Chaos Orb"] := 1
ITEMS_OF_INTEREST["Contract"] := 3
ITEMS_OF_INTEREST["Blueprint"] := 10
ITEMS_OF_INTEREST["Rogue's Marker"] := 0.004
ITEMS_OF_INTEREST["Occupied Map"] := 20
ITEMS_OF_INTEREST["Mirror of Kalandra"] := 65632.47
ITEMS_OF_INTEREST["Mirror Shard"] := 3224.63
ITEMS_OF_INTEREST["Tempering Orb"] := 904.97
ITEMS_OF_INTEREST["Tailoring Orb"] := 447.75
ITEMS_OF_INTEREST["Secondary Regrading Lens"] := 441.41
ITEMS_OF_INTEREST["Maven's Orb"] := 270.27
ITEMS_OF_INTEREST["Orb of Dominance"] := 224.27
ITEMS_OF_INTEREST["Exalted Orb"] := 181.91
ITEMS_OF_INTEREST["Awakener's Orb"] := 179.48
ITEMS_OF_INTEREST["Hunter's Exalted Orb"] := 177.58
ITEMS_OF_INTEREST["Prime Regrading Lens"] := 95.28
ITEMS_OF_INTEREST["Crusader's Exalted Orb"] := 87.82
ITEMS_OF_INTEREST["Redeemer's Exalted Orb"] := 74.05
ITEMS_OF_INTEREST["Warlord's Exalted Orb"] := 73.9
ITEMS_OF_INTEREST["Sacred Orb"] := 48.39
ITEMS_OF_INTEREST["Eldritch Chaos Orb"] := 31.65
ITEMS_OF_INTEREST["Elevated Sextant"] := 30.49
ITEMS_OF_INTEREST["Orb of Conflict"] := 24.91
ITEMS_OF_INTEREST["Blessing of Chayula"] := 24.63
ITEMS_OF_INTEREST["Eldritch Exalted Orb"] := 23.28
ITEMS_OF_INTEREST["Exceptional Eldritch Ichor"] := 20.18
ITEMS_OF_INTEREST["Eldritch Orb of Annulment"] := 19.45
ITEMS_OF_INTEREST["Exceptional Eldritch Ember"] := 15.07
ITEMS_OF_INTEREST["Veiled Chaos Orb"] := 11.33
ITEMS_OF_INTEREST["Blessing of Tul"] := 10.98
ITEMS_OF_INTEREST["Ancient Orb"] := 10.24
ITEMS_OF_INTEREST["Blessing of Uul-Netol"] := 10.02
ITEMS_OF_INTEREST["Tainted Blessing"] := 10
ITEMS_OF_INTEREST["Blessing of Xoph"] := 8.91
ITEMS_OF_INTEREST["Blessing of Esh"] := 8.91
ITEMS_OF_INTEREST["Exalted Shard"] := 8.78
ITEMS_OF_INTEREST["Jewellery Recombinator"] := 8.11
ITEMS_OF_INTEREST["Divine Orb"] := 8.07
ITEMS_OF_INTEREST["Armour Recombinator"] := 6.9
ITEMS_OF_INTEREST["Prismatic Catalyst"] := 6.89
ITEMS_OF_INTEREST["Orb of Annulment"] := 6.23
ITEMS_OF_INTEREST["Oil Extractor"] := 6.06
ITEMS_OF_INTEREST["Otherworldly Scouting Report"] := 5.71
ITEMS_OF_INTEREST["Weapon Recombinator"] := 5.52
ITEMS_OF_INTEREST["Unstable Catalyst"] := 5
ITEMS_OF_INTEREST["Infused Engineer's Orb"] := 5
ITEMS_OF_INTEREST["Ritual Vessel"] := 4.81
ITEMS_OF_INTEREST["Influenced Scouting Report"] := 4.56
ITEMS_OF_INTEREST["Transforming Power Core"] := 4.56
ITEMS_OF_INTEREST["Charged Compass"] := 4
ITEMS_OF_INTEREST["Comprehensive Scouting Report"] := 4
ITEMS_OF_INTEREST["Blighted Scouting Report"] := 4
ITEMS_OF_INTEREST["Fertile Catalyst"] := 3.92
ITEMS_OF_INTEREST["Amplifying Power Core"] := 3.03
ITEMS_OF_INTEREST["Grand Eldritch Ember"] := 2.88
ITEMS_OF_INTEREST["Awakened Sextant"] := 2.85
ITEMS_OF_INTEREST["Delirious Scouting Report"] := 2.55
ITEMS_OF_INTEREST["Grand Eldritch Ichor"] := 2.52
ITEMS_OF_INTEREST["Augmenting Power Core"] := 2.47
ITEMS_OF_INTEREST["Stacked Deck"] := 2
ITEMS_OF_INTEREST["Operative's Scouting Report"] := 2
ITEMS_OF_INTEREST["Greater Eldritch Ember"] := 1.97
ITEMS_OF_INTEREST["Harbinger's Orb"] := 1.46
ITEMS_OF_INTEREST["Orb of Unmaking"] := 1.42
ITEMS_OF_INTEREST["Annulment Shard"] := 1
ITEMS_OF_INTEREST["Tempering Catalyst"] := 1
ITEMS_OF_INTEREST["Accelerating Catalyst"] := 1
ITEMS_OF_INTEREST["Singular Scouting Report"] := 1
ITEMS_OF_INTEREST["Greater Eldritch Ichor"] := 0.99
ITEMS_OF_INTEREST["Lesser Eldritch Ember"] := 0.93
ITEMS_OF_INTEREST["Orb of Regret"] := 0.79
ITEMS_OF_INTEREST["Enkindling Orb"] := 0.71
ITEMS_OF_INTEREST["Noxious Catalyst"] := 0.66
ITEMS_OF_INTEREST["Vaal Scouting Report"] := 0.65
ITEMS_OF_INTEREST["Vaal Orb"] := 0.64
ITEMS_OF_INTEREST["Blessed Orb"] := 0.64
ITEMS_OF_INTEREST["Lesser Eldritch Ichor"] := 0.58
ITEMS_OF_INTEREST["Surveyor's Compass"] := 0.56
ITEMS_OF_INTEREST["Orb of Scouring"] := 0.53
ITEMS_OF_INTEREST["Gemcutter's Prism"] := 0.53
ITEMS_OF_INTEREST["Instilling Orb"] := 0.49
ITEMS_OF_INTEREST["Regal Orb"] := 0.39
ITEMS_OF_INTEREST["Intrinsic Catalyst"] := 0.33
ITEMS_OF_INTEREST["Abrasive Catalyst"] := 0.3
ITEMS_OF_INTEREST["Orb of Alteration"] := 0.22
ITEMS_OF_INTEREST["Explorer's Scouting Report"] := 0.22
ITEMS_OF_INTEREST["Glassblower's Bauble"] := 0.21
ITEMS_OF_INTEREST["Orb of Horizons"] := 0.21
ITEMS_OF_INTEREST["Orb of Fusing"] := 0.19
ITEMS_OF_INTEREST["Orb of Alchemy"] := 0.16
ITEMS_OF_INTEREST["Turbulent Catalyst"] := 0.16
ITEMS_OF_INTEREST["Orb of Binding"] := 0.13
ITEMS_OF_INTEREST["Power Core"] := 0.12
ITEMS_OF_INTEREST["Imbued Catalyst"] := 0.1
ITEMS_OF_INTEREST["Orb of Chance"] := 0.09
ITEMS_OF_INTEREST["Chromatic Orb"] := 0.09
ITEMS_OF_INTEREST["Cartographer's Chisel"] := 0.07
ITEMS_OF_INTEREST["Orb of Augmentation"] := 0.07
ITEMS_OF_INTEREST["Jeweller's Orb"] := 0.05
ITEMS_OF_INTEREST["Engineer's Orb"] := 0.05
ITEMS_OF_INTEREST["Portal Scroll"] := 0.03
ITEMS_OF_INTEREST["Blacksmith's Whetstone"] := 0.03
ITEMS_OF_INTEREST["Orb of Transmutation"] := 0.02
ITEMS_OF_INTEREST["Armourer's Scrap"] := 0.02
ITEMS_OF_INTEREST["Uul-Netol's Flawless Breachstone"] := 360
ITEMS_OF_INTEREST["Chayula's Flawless Breachstone"] := 168.18
ITEMS_OF_INTEREST["Chayula's Pure Breachstone"] := 124.01
ITEMS_OF_INTEREST["Xoph's Flawless Breachstone"] := 107.81
ITEMS_OF_INTEREST["Tul's Flawless Breachstone"] := 107.81
ITEMS_OF_INTEREST["Esh's Flawless Breachstone"] := 107.81
ITEMS_OF_INTEREST["The Maven's Writ"] := 93.62
ITEMS_OF_INTEREST["Timeless Maraketh Emblem"] := 90.39
ITEMS_OF_INTEREST["Gift to the Goddess"] := 89.57
ITEMS_OF_INTEREST["Fragment of Shape"] := 85.6
ITEMS_OF_INTEREST["Fragment of Knowledge"] := 83.58
ITEMS_OF_INTEREST["Unrelenting Timeless Maraketh Emblem"] := 69.98
ITEMS_OF_INTEREST["Uul-Netol's Pure Breachstone"] := 69
ITEMS_OF_INTEREST["Unrelenting Timeless Karui Emblem"] := 59.99
ITEMS_OF_INTEREST["Unrelenting Timeless Eternal Emblem"] := 59.99
ITEMS_OF_INTEREST["Unrelenting Timeless Templar Emblem"] := 59.99
ITEMS_OF_INTEREST["Unrelenting Timeless Vaal Emblem"] := 59.99
ITEMS_OF_INTEREST["Uul-Netol's Enriched Breachstone"] := 58
ITEMS_OF_INTEREST["Chayula's Enriched Breachstone"] := 51.85
ITEMS_OF_INTEREST["Xoph's Pure Breachstone"] := 51.41
ITEMS_OF_INTEREST["Tul's Pure Breachstone"] := 51.41
ITEMS_OF_INTEREST["Esh's Pure Breachstone"] := 51.41
ITEMS_OF_INTEREST["Chayula's Breachstone"] := 44.52
ITEMS_OF_INTEREST["Simulacrum"] := 38.84
ITEMS_OF_INTEREST["Uul-Netol's Charged Breachstone"] := 35
ITEMS_OF_INTEREST["Chayula's Charged Breachstone"] := 30.85
ITEMS_OF_INTEREST["Fragment of Emptiness"] := 27.5
ITEMS_OF_INTEREST["Fragment of Terror"] := 26.14
ITEMS_OF_INTEREST["Timeless Templar Emblem"] := 22.06
ITEMS_OF_INTEREST["Esh's Enriched Breachstone"] := 21
ITEMS_OF_INTEREST["Uul-Netol's Breachstone"] := 19.93
ITEMS_OF_INTEREST["Fragment of Eradication"] := 19.72
ITEMS_OF_INTEREST["Fragment of Enslavement"] := 15.9
ITEMS_OF_INTEREST["Fragment of Purification"] := 15.87
ITEMS_OF_INTEREST["Tul's Enriched Breachstone"] := 15.85
ITEMS_OF_INTEREST["Fragment of Constriction"] := 14.95
ITEMS_OF_INTEREST["Fragment of the Chimera"] := 14.73
ITEMS_OF_INTEREST["Fragment of the Phoenix"] := 14.34
ITEMS_OF_INTEREST["Fragment of the Hydra"] := 13.81
ITEMS_OF_INTEREST["Fragment of the Minotaur"] := 12.85
ITEMS_OF_INTEREST["Xoph's Enriched Breachstone"] := 12.85
ITEMS_OF_INTEREST["Xoph's Breachstone"] := 11.92
ITEMS_OF_INTEREST["Xoph's Charged Breachstone"] := 11
ITEMS_OF_INTEREST["Tul's Charged Breachstone"] := 11
ITEMS_OF_INTEREST["Esh's Charged Breachstone"] := 11
ITEMS_OF_INTEREST["Tul's Breachstone"] := 10.96
ITEMS_OF_INTEREST["Al-Hezmin's Crest"] := 10.87
ITEMS_OF_INTEREST["Drox's Crest"] := 10.84
ITEMS_OF_INTEREST["Veritania's Crest"] := 10.84
ITEMS_OF_INTEREST["Esh's Breachstone"] := 9.96
ITEMS_OF_INTEREST["Crescent Splinter"] := 9.9
ITEMS_OF_INTEREST["Baran's Crest"] := 9.75
ITEMS_OF_INTEREST["Mortal Ignorance"] := 7.76
ITEMS_OF_INTEREST["Dedication to the Goddess"] := 6.34
ITEMS_OF_INTEREST["Timeless Vaal Emblem"] := 5.89
ITEMS_OF_INTEREST["Timeless Karui Emblem"] := 5.01
ITEMS_OF_INTEREST["Timeless Eternal Emblem"] := 5.01
ITEMS_OF_INTEREST["Mortal Rage"] := 3.9
ITEMS_OF_INTEREST["Mortal Hope"] := 3.63
ITEMS_OF_INTEREST["Mortal Grief"] := 1.99
ITEMS_OF_INTEREST["Divine Vessel"] := 1.76
ITEMS_OF_INTEREST["Tribute to the Goddess"] := 1.53
ITEMS_OF_INTEREST["Timeless Maraketh Splinter"] := 0.59
ITEMS_OF_INTEREST["Splinter of Uul-Netol"] := 0.43
ITEMS_OF_INTEREST["Splinter of Chayula"] := 0.35
ITEMS_OF_INTEREST["Sacrifice at Midnight"] := 0.22
ITEMS_OF_INTEREST["Simulacrum Splinter"] := 0.19
ITEMS_OF_INTEREST["Timeless Templar Splinter"] := 0.18
ITEMS_OF_INTEREST["Sacrifice at Noon"] := 0.11
ITEMS_OF_INTEREST["Offering to the Goddess"] := 0.1
ITEMS_OF_INTEREST["Sacrifice at Dawn"] := 0.08
ITEMS_OF_INTEREST["Sacrifice at Dusk"] := 0.07
ITEMS_OF_INTEREST["Splinter of Xoph"] := 0.05
ITEMS_OF_INTEREST["Splinter of Tul"] := 0.05
ITEMS_OF_INTEREST["Splinter of Esh"] := 0.05
ITEMS_OF_INTEREST["Timeless Karui Splinter"] := 0.05
ITEMS_OF_INTEREST["Timeless Eternal Empire Splinter"] := 0.05
ITEMS_OF_INTEREST["Timeless Vaal Splinter"] := 0.05
ITEMS_OF_INTEREST["Tainted Oil"] := 160
ITEMS_OF_INTEREST["Golden Oil"] := 47
ITEMS_OF_INTEREST["Silver Oil"] := 19
ITEMS_OF_INTEREST["Opalescent Oil"] := 8
ITEMS_OF_INTEREST["Black Oil"] := 2.21
ITEMS_OF_INTEREST["Crimson Oil"] := 2
ITEMS_OF_INTEREST["Violet Oil"] := 1
ITEMS_OF_INTEREST["Verdant Oil"] := 0.5
ITEMS_OF_INTEREST["Clear Oil"] := 0.5
ITEMS_OF_INTEREST["Teal Oil"] := 0.5
ITEMS_OF_INTEREST["Azure Oil"] := 0.5
ITEMS_OF_INTEREST["Indigo Oil"] := 0.5
ITEMS_OF_INTEREST["Sepia Oil"] := 0.43
ITEMS_OF_INTEREST["Amber Oil"] := 0.43
ITEMS_OF_INTEREST["Geomancer's Incubator"] := 9.49
ITEMS_OF_INTEREST["Time-Lost Incubator"] := 7.58
ITEMS_OF_INTEREST["Morphing Incubator"] := 5.24
ITEMS_OF_INTEREST["Cartographer's Incubator"] := 5
ITEMS_OF_INTEREST["Skittering Incubator"] := 5
ITEMS_OF_INTEREST["Diviner's Incubator"] := 5
ITEMS_OF_INTEREST["Thaumaturge's Incubator"] := 5
ITEMS_OF_INTEREST["Mysterious Incubator"] := 5
ITEMS_OF_INTEREST["Foreboding Incubator"] := 5
ITEMS_OF_INTEREST["Maddening Incubator"] := 5
ITEMS_OF_INTEREST["Blighted Incubator"] := 5
ITEMS_OF_INTEREST["Kalguuran Incubator"] := 5
ITEMS_OF_INTEREST["Infused Incubator"] := 4.9
ITEMS_OF_INTEREST["Otherworldly Incubator"] := 4.84
ITEMS_OF_INTEREST["Obscured Incubator"] := 4.64
ITEMS_OF_INTEREST["Primal Incubator"] := 4.55
ITEMS_OF_INTEREST["Abyssal Incubator"] := 4.38
ITEMS_OF_INTEREST["Celestial Armoursmith's Incubator"] := 4.36
ITEMS_OF_INTEREST["Ornate Incubator"] := 4.17
ITEMS_OF_INTEREST["Fragmented Incubator"] := 4.06
ITEMS_OF_INTEREST["Singular Incubator"] := 4
ITEMS_OF_INTEREST["Celestial Jeweller's Incubator"] := 4
ITEMS_OF_INTEREST["Enchanted Incubator"] := 4
ITEMS_OF_INTEREST["Fossilised Incubator"] := 4
ITEMS_OF_INTEREST["Celestial Blacksmith's Incubator"] := 4
ITEMS_OF_INTEREST["Lair of the Hydra Map"] := 8.51
ITEMS_OF_INTEREST["Forge of the Phoenix Map"] := 8.45
ITEMS_OF_INTEREST["Carcass Map"] := 1
ITEMS_OF_INTEREST["Strand Map"] := 4
ITEMS_OF_INTEREST["Mesa Map"] := 1
ITEMS_OF_INTEREST["City Square Map"] := 1
ITEMS_OF_INTEREST["Maze of the Minotaur Map"] := 5.12
ITEMS_OF_INTEREST["Beach Map"] := 4.99
ITEMS_OF_INTEREST["Park Map"] := 3.98
ITEMS_OF_INTEREST["Pit of the Chimera Map"] := 5
ITEMS_OF_INTEREST["Vaal Temple Map"] := 5
ITEMS_OF_INTEREST["Waste Pool Map"] := 1
ITEMS_OF_INTEREST["Atoll Map"] := 2
ITEMS_OF_INTEREST["Tower Map"] := 1
ITEMS_OF_INTEREST["Ashen Wood Map"] := 1
ITEMS_OF_INTEREST["Wharf Map"] := 4
ITEMS_OF_INTEREST["Glacier Map"] := 2
ITEMS_OF_INTEREST["Alleyways Map"] := 4
ITEMS_OF_INTEREST["Palace Map"] := 3
ITEMS_OF_INTEREST["Infested Valley Map"] := 1
ITEMS_OF_INTEREST["Core Map"] := 1
ITEMS_OF_INTEREST["Promenade Map"] := 1
ITEMS_OF_INTEREST["Tropical Island Map"] := 1
ITEMS_OF_INTEREST["Mineral Pools Map"] := 1.23
ITEMS_OF_INTEREST["Moon Temple Map"] := 1
ITEMS_OF_INTEREST["Dark Forest Map"] := 1.56
ITEMS_OF_INTEREST["Grave Trough Map"] := 1
ITEMS_OF_INTEREST["Fields Map"] := 4
ITEMS_OF_INTEREST["Canyon Map"] := 1
ITEMS_OF_INTEREST["Cemetery Map"] := 1
ITEMS_OF_INTEREST["Burial Chambers Map"] := 4
ITEMS_OF_INTEREST["Lava Lake Map"] := 4
ITEMS_OF_INTEREST["Cursed Crypt Map"] := 4
ITEMS_OF_INTEREST["Fungal Hollow Map"] := 4
ITEMS_OF_INTEREST["Barrows Map"] := 4
ITEMS_OF_INTEREST["Ramparts Map"] := 1
ITEMS_OF_INTEREST["Frozen Cabins Map"] := 1
ITEMS_OF_INTEREST["Port Map"] := 3
ITEMS_OF_INTEREST["Cells Map"] := 3.02
ITEMS_OF_INTEREST["Overgrown Shrine Map"] := 1
ITEMS_OF_INTEREST["Acid Caverns Map"] := 1
ITEMS_OF_INTEREST["Toxic Sewer Map"] := 1
ITEMS_OF_INTEREST["Arsenal Map"] := 1
ITEMS_OF_INTEREST["Overgrown Ruin Map"] := 1
ITEMS_OF_INTEREST["Dry Sea Map"] := 1
ITEMS_OF_INTEREST["Underground Sea Map"] := 0.32
ITEMS_OF_INTEREST["Villa Map"] := 1.46
ITEMS_OF_INTEREST["Summit Map"] := 1.65
ITEMS_OF_INTEREST["Museum Map"] := 1
ITEMS_OF_INTEREST["Crimson Temple Map"] := 1
ITEMS_OF_INTEREST["Temple Map"] := 1
ITEMS_OF_INTEREST["Reef Map"] := 1
ITEMS_OF_INTEREST["Jungle Valley Map"] := 2.5
ITEMS_OF_INTEREST["Bone Crypt Map"] := 1
ITEMS_OF_INTEREST["Cage Map"] := 3.03
ITEMS_OF_INTEREST["Precinct Map"] := 3.65
ITEMS_OF_INTEREST["Foundry Map"] := 4
ITEMS_OF_INTEREST["Underground River Map"] := 2.1
ITEMS_OF_INTEREST["Orchard Map"] := 1
ITEMS_OF_INTEREST["Desert Map"] := 1
ITEMS_OF_INTEREST["Thicket Map"] := 1
ITEMS_OF_INTEREST["Sepulchre Map"] := 1
ITEMS_OF_INTEREST["Ivory Temple Map"] := 1
ITEMS_OF_INTEREST["Lava Chamber Map"] := 1
ITEMS_OF_INTEREST["Gardens Map"] := 1
ITEMS_OF_INTEREST["Courtyard Map"] := 1
ITEMS_OF_INTEREST["Terrace Map"] := 1
ITEMS_OF_INTEREST["Wasteland Map"] := 2
ITEMS_OF_INTEREST["Dunes Map"] := 2
ITEMS_OF_INTEREST["Grotto Map"] := 1
ITEMS_OF_INTEREST["Lookout Map"] := 1
ITEMS_OF_INTEREST["Colonnade Map"] := 2
ITEMS_OF_INTEREST["Bazaar Map"] := 1
ITEMS_OF_INTEREST["Laboratory Map"] := 4
ITEMS_OF_INTEREST["Mausoleum Map"] := 2
ITEMS_OF_INTEREST["Arcade Map"] := 1
ITEMS_OF_INTEREST["Pit Map"] := 3
ITEMS_OF_INTEREST["Necropolis Map"] := 1
ITEMS_OF_INTEREST["Plaza Map"] := 1
ITEMS_OF_INTEREST["Primordial Pool Map"] := 1
ITEMS_OF_INTEREST["Mud Geyser Map"] := 1.54
ITEMS_OF_INTEREST["Volcano Map"] := 1.68
ITEMS_OF_INTEREST["Peninsula Map"] := 1
ITEMS_OF_INTEREST["Armoury Map"] := 1.79
ITEMS_OF_INTEREST["Desert Spring Map"] := 1
ITEMS_OF_INTEREST["Basilica Map"] := 1.66
ITEMS_OF_INTEREST["Cold River Map"] := 1
ITEMS_OF_INTEREST["Crimson Township Map"] := 2
ITEMS_OF_INTEREST["Lair Map"] := 1
ITEMS_OF_INTEREST["Dungeon Map"] := 1
ITEMS_OF_INTEREST["Bog Map"] := 1
ITEMS_OF_INTEREST["Arid Lake Map"] := 1
ITEMS_OF_INTEREST["Spider Forest Map"] := 4
ITEMS_OF_INTEREST["Factory Map"] := 1.43
ITEMS_OF_INTEREST["Caldera Map"] := 3.89
ITEMS_OF_INTEREST["Vaal Pyramid Map"] := 1.83
ITEMS_OF_INTEREST["Sunken City Map"] := 1.67
ITEMS_OF_INTEREST["Bramble Valley Map"] := 1
ITEMS_OF_INTEREST["Coral Ruins Map"] := 1.45
ITEMS_OF_INTEREST["Shore Map"] := 1
ITEMS_OF_INTEREST["Residence Map"] := 3
ITEMS_OF_INTEREST["Maze Map"] := 1
ITEMS_OF_INTEREST["Crystal Ore Map"] := 1
ITEMS_OF_INTEREST["Arena Map"] := 1.73
ITEMS_OF_INTEREST["Marshes Map"] := 1
ITEMS_OF_INTEREST["Blighted Cold River Map"] := 5.66
ITEMS_OF_INTEREST["Blighted Crimson Township Map"] := 7
ITEMS_OF_INTEREST["Blighted Overgrown Shrine Map"] := 6
ITEMS_OF_INTEREST["Blighted Bazaar Map"] := 6
ITEMS_OF_INTEREST["Blighted Lookout Map"] := 7
ITEMS_OF_INTEREST["Blighted Moon Temple Map"] := 5.64
ITEMS_OF_INTEREST["Blighted Ramparts Map"] := 6
ITEMS_OF_INTEREST["Blighted Bramble Valley Map"] := 6
ITEMS_OF_INTEREST["Blighted Dry Sea Map"] := 6
ITEMS_OF_INTEREST["Blighted Ivory Temple Map"] := 7
ITEMS_OF_INTEREST["Blighted Crimson Temple Map"] := 6
ITEMS_OF_INTEREST["Blighted Reef Map"] := 6
ITEMS_OF_INTEREST["Blighted Peninsula Map"] := 6
ITEMS_OF_INTEREST["Blighted Plaza Map"] := 6
ITEMS_OF_INTEREST["Blighted Dungeon Map"] := 5.8
ITEMS_OF_INTEREST["Blighted Thicket Map"] := 6
ITEMS_OF_INTEREST["Blighted Courtyard Map"] := 7
ITEMS_OF_INTEREST["Blighted Arid Lake Map"] := 6
ITEMS_OF_INTEREST["Blighted Orchard Map"] := 6
ITEMS_OF_INTEREST["Blighted Acid Caverns Map"] := 6
ITEMS_OF_INTEREST["Blighted Armoury Map"] := 6
ITEMS_OF_INTEREST["Blighted Necropolis Map"] := 6
ITEMS_OF_INTEREST["Blighted Gardens Map"] := 7
ITEMS_OF_INTEREST["Blighted Ashen Wood Map"] := 6
ITEMS_OF_INTEREST["Blighted Mud Geyser Map"] := 6
ITEMS_OF_INTEREST["Blighted Burial Chambers Map"] := 20
ITEMS_OF_INTEREST["Blighted Strand Map"] := 15.5
ITEMS_OF_INTEREST["Blighted Wharf Map"] := 10
ITEMS_OF_INTEREST["Blighted Arcade Map"] := 6
ITEMS_OF_INTEREST["Blighted Waste Pool Map"] := 10
ITEMS_OF_INTEREST["Blighted Palace Map"] := 18
ITEMS_OF_INTEREST["Blighted Laboratory Map"] := 15
ITEMS_OF_INTEREST["Blighted Cage Map"] := 10
ITEMS_OF_INTEREST["Blighted Lava Chamber Map"] := 7.95
ITEMS_OF_INTEREST["Blighted Summit Map"] := 6
ITEMS_OF_INTEREST["Blighted Port Map"] := 10
ITEMS_OF_INTEREST["Blighted Mineral Pools Map"] := 10
ITEMS_OF_INTEREST["Blighted Promenade Map"] := 7
ITEMS_OF_INTEREST["Blighted Beach Map"] := 17
ITEMS_OF_INTEREST["Blighted Underground River Map"] := 10
ITEMS_OF_INTEREST["Blighted Fields Map"] := 15
ITEMS_OF_INTEREST["Blighted Pit Map"] := 10
ITEMS_OF_INTEREST["Blighted Tropical Island Map"] := 7
ITEMS_OF_INTEREST["Blighted Cemetery Map"] := 6
ITEMS_OF_INTEREST["Blighted Arsenal Map"] := 5.33
ITEMS_OF_INTEREST["Blighted Barrows Map"] := 18
ITEMS_OF_INTEREST["Blighted Bog Map"] := 6
ITEMS_OF_INTEREST["Blighted Toxic Sewer Map"] := 6.35
ITEMS_OF_INTEREST["Blighted Dark Forest Map"] := 9
ITEMS_OF_INTEREST["Blighted City Square Map"] := 6.89
ITEMS_OF_INTEREST["Blighted Mesa Map"] := 7
ITEMS_OF_INTEREST["Blighted Tower Map"] := 6
ITEMS_OF_INTEREST["Blighted Lair Map"] := 7
ITEMS_OF_INTEREST["Blighted Bone Crypt Map"] := 7
ITEMS_OF_INTEREST["Blighted Wasteland Map"] := 15
ITEMS_OF_INTEREST["Blighted Sepulchre Map"] := 7
ITEMS_OF_INTEREST["Blighted Temple Map"] := 6
ITEMS_OF_INTEREST["Blighted Spider Forest Map"] := 5.24
ITEMS_OF_INTEREST["Blighted Villa Map"] := 17.66
ITEMS_OF_INTEREST["Blighted Atoll Map"] := 6
ITEMS_OF_INTEREST["Blighted Foundry Map"] := 10
ITEMS_OF_INTEREST["Blighted Basilica Map"] := 6
ITEMS_OF_INTEREST["Blighted Grave Trough Map"] := 10
ITEMS_OF_INTEREST["Blighted Lava Lake Map"] := 19.73
ITEMS_OF_INTEREST["Blighted Precinct Map"] := 10
ITEMS_OF_INTEREST["Blighted Caldera Map"] := 19.59
ITEMS_OF_INTEREST["Blighted Underground Sea Map"] := 6
ITEMS_OF_INTEREST["Blighted Infested Valley Map"] := 6
ITEMS_OF_INTEREST["Blighted Alleyways Map"] := 17
ITEMS_OF_INTEREST["Blighted Dunes Map"] := 9.44
ITEMS_OF_INTEREST["Blighted Desert Spring Map"] := 7
ITEMS_OF_INTEREST["Blighted Volcano Map"] := 6
ITEMS_OF_INTEREST["Blighted Colonnade Map"] := 7
ITEMS_OF_INTEREST["Blighted Cursed Crypt Map"] := 18
ITEMS_OF_INTEREST["Blighted Desert Map"] := 7
ITEMS_OF_INTEREST["Blighted Canyon Map"] := 9.65
ITEMS_OF_INTEREST["Blighted Coral Ruins Map"] := 14
ITEMS_OF_INTEREST["Blighted Cells Map"] := 18
ITEMS_OF_INTEREST["Blighted Shore Map"] := 6.6
ITEMS_OF_INTEREST["Blighted Glacier Map"] := 7
ITEMS_OF_INTEREST["Blighted Mausoleum Map"] := 9
ITEMS_OF_INTEREST["Blighted Marshes Map"] := 9
ITEMS_OF_INTEREST["Blighted Museum Map"] := 6
ITEMS_OF_INTEREST["Blighted Primordial Pool Map"] := 6
ITEMS_OF_INTEREST["Blighted Park Map"] := 17
ITEMS_OF_INTEREST["Blighted Jungle Valley Map"] := 10
ITEMS_OF_INTEREST["Doryani's Machinarium"] := 362.26
ITEMS_OF_INTEREST["Cortex"] := 362.26
ITEMS_OF_INTEREST["Replica Cortex"] := 307.92
ITEMS_OF_INTEREST["Twisted Distant Memory"] := 60
ITEMS_OF_INTEREST["Rewritten Distant Memory"] := 60
ITEMS_OF_INTEREST["Augmented Distant Memory"] := 50
ITEMS_OF_INTEREST["Altered Distant Memory"] := 50
ITEMS_OF_INTEREST["The Vinktar Square"] := 44.54
ITEMS_OF_INTEREST["Infused Beachhead"] := 29
ITEMS_OF_INTEREST["The Coward's Trial"] := 25
ITEMS_OF_INTEREST["Replica Poorjoy's Asylum"] := 20
ITEMS_OF_INTEREST["The Putrid Cloister"] := 8.24
ITEMS_OF_INTEREST["The Beachhead"] := 10
ITEMS_OF_INTEREST["The Twilight Temple"] := 7
ITEMS_OF_INTEREST["Mao Kun"] := 4.74
ITEMS_OF_INTEREST["Caer Blaidd, Wolfpack's Den"] := 5
ITEMS_OF_INTEREST["Poorjoy's Asylum"] := 5
ITEMS_OF_INTEREST["Replica Pillars of Arun"] := 5
ITEMS_OF_INTEREST["Hallowed Ground"] := 4
ITEMS_OF_INTEREST["Death and Taxes"] := 4
ITEMS_OF_INTEREST["Vaults of Atziri"] := 3
ITEMS_OF_INTEREST["Maelström of Chaos"] := 2
ITEMS_OF_INTEREST["Olmec's Sanctum"] := 2
ITEMS_OF_INTEREST["Oba's Cursed Trove"] := 2
ITEMS_OF_INTEREST["Acton's Nightmare"] := 2
ITEMS_OF_INTEREST["Pillars of Arun"] := 2
ITEMS_OF_INTEREST["Whakawairua Tuahu"] := 2
ITEMS_OF_INTEREST["Hall of Grandmasters"] := 1
ITEMS_OF_INTEREST["Skittering Delirium Orb"] := 60.38
ITEMS_OF_INTEREST["Diviner's Delirium Orb"] := 31
ITEMS_OF_INTEREST["Cartographer's Delirium Orb"] := 26
ITEMS_OF_INTEREST["Fine Delirium Orb"] := 19
ITEMS_OF_INTEREST["Foreboding Delirium Orb"] := 15
ITEMS_OF_INTEREST["Singular Delirium Orb"] := 13
ITEMS_OF_INTEREST["Fossilised Delirium Orb"] := 12
ITEMS_OF_INTEREST["Fragmented Delirium Orb"] := 11
ITEMS_OF_INTEREST["Jeweller's Delirium Orb"] := 11
ITEMS_OF_INTEREST["Abyssal Delirium Orb"] := 11
ITEMS_OF_INTEREST["Obscured Delirium Orb"] := 11
ITEMS_OF_INTEREST["Armoursmith's Delirium Orb"] := 11
ITEMS_OF_INTEREST["Thaumaturge's Delirium Orb"] := 11
ITEMS_OF_INTEREST["Amorphous Delirium Orb"] := 11
ITEMS_OF_INTEREST["Whispering Delirium Orb"] := 11
ITEMS_OF_INTEREST["Blacksmith's Delirium Orb"] := 10.82
ITEMS_OF_INTEREST["Imperial Delirium Orb"] := 10
ITEMS_OF_INTEREST["Blighted Delirium Orb"] := 10
ITEMS_OF_INTEREST["Timeless Delirium Orb"] := 10
ITEMS_OF_INTEREST["Winged Divination Scarab"] := 70
ITEMS_OF_INTEREST["Winged Reliquary Scarab"] := 68
ITEMS_OF_INTEREST["Winged Abyss Scarab"] := 65
ITEMS_OF_INTEREST["Winged Harbinger Scarab"] := 57.64
ITEMS_OF_INTEREST["Winged Ambush Scarab"] := 45.62
ITEMS_OF_INTEREST["Winged Breach Scarab"] := 35
ITEMS_OF_INTEREST["Gilded Divination Scarab"] := 27
ITEMS_OF_INTEREST["Winged Expedition Scarab"] := 21.39
ITEMS_OF_INTEREST["Craicic Lure"] := 20
ITEMS_OF_INTEREST["Gilded Ambush Scarab"] := 15
ITEMS_OF_INTEREST["Winged Legion Scarab"] := 15
ITEMS_OF_INTEREST["Winged Cartography Scarab"] := 12
ITEMS_OF_INTEREST["Winged Blight Scarab"] := 12
ITEMS_OF_INTEREST["Gilded Expedition Scarab"] := 12
ITEMS_OF_INTEREST["Winged Shaper Scarab"] := 11.92
ITEMS_OF_INTEREST["Winged Sulphite Scarab"] := 11
ITEMS_OF_INTEREST["Winged Metamorph Scarab"] := 11
ITEMS_OF_INTEREST["Winged Bestiary Scarab"] := 11
ITEMS_OF_INTEREST["Winged Elder Scarab"] := 11
ITEMS_OF_INTEREST["Winged Torment Scarab"] := 11
ITEMS_OF_INTEREST["Gilded Harbinger Scarab"] := 10.62
ITEMS_OF_INTEREST["Gilded Reliquary Scarab"] := 10
ITEMS_OF_INTEREST["Polished Divination Scarab"] := 9
ITEMS_OF_INTEREST["Fenumal Lure"] := 9
ITEMS_OF_INTEREST["Saqawine Lure"] := 8.97
ITEMS_OF_INTEREST["Gilded Abyss Scarab"] := 8.2
ITEMS_OF_INTEREST["Polished Ambush Scarab"] := 8
ITEMS_OF_INTEREST["Gilded Breach Scarab"] := 6
ITEMS_OF_INTEREST["Polished Expedition Scarab"] := 6
ITEMS_OF_INTEREST["Gilded Legion Scarab"] := 5.26
ITEMS_OF_INTEREST["Polished Harbinger Scarab"] := 5.05
ITEMS_OF_INTEREST["Rusted Ambush Scarab"] := 4
ITEMS_OF_INTEREST["Farric Lure"] := 4
ITEMS_OF_INTEREST["Gilded Blight Scarab"] := 4
ITEMS_OF_INTEREST["Gilded Cartography Scarab"] := 3
ITEMS_OF_INTEREST["Rusted Divination Scarab"] := 2.98
ITEMS_OF_INTEREST["Polished Cartography Scarab"] := 2.5
ITEMS_OF_INTEREST["Rusted Expedition Scarab"] := 2.35
ITEMS_OF_INTEREST["Gilded Bestiary Scarab"] := 2
ITEMS_OF_INTEREST["Gilded Sulphite Scarab"] := 2
ITEMS_OF_INTEREST["Rusted Harbinger Scarab"] := 1.99
ITEMS_OF_INTEREST["Polished Breach Scarab"] := 1.57
ITEMS_OF_INTEREST["Polished Legion Scarab"] := 1.5
ITEMS_OF_INTEREST["Gilded Elder Scarab"] := 1.47
ITEMS_OF_INTEREST["Gilded Metamorph Scarab"] := 1.22
ITEMS_OF_INTEREST["Rusted Cartography Scarab"] := 1
ITEMS_OF_INTEREST["Rusted Elder Scarab"] := 1
ITEMS_OF_INTEREST["Gilded Torment Scarab"] := 1
ITEMS_OF_INTEREST["Gilded Shaper Scarab"] := 1
ITEMS_OF_INTEREST["Polished Elder Scarab"] := 1
ITEMS_OF_INTEREST["Polished Bestiary Scarab"] := 1
ITEMS_OF_INTEREST["Polished Reliquary Scarab"] := 1
ITEMS_OF_INTEREST["Polished Abyss Scarab"] := 1
ITEMS_OF_INTEREST["Polished Blight Scarab"] := 1
ITEMS_OF_INTEREST["Rusted Reliquary Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Bestiary Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Torment Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Breach Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Shaper Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Sulphite Scarab"] := 0.5
ITEMS_OF_INTEREST["Polished Shaper Scarab"] := 0.5
ITEMS_OF_INTEREST["Polished Sulphite Scarab"] := 0.5
ITEMS_OF_INTEREST["Polished Torment Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Legion Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Metamorph Scarab"] := 0.5
ITEMS_OF_INTEREST["Polished Metamorph Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Blight Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Abyss Scarab"] := 0.5
ITEMS_OF_INTEREST["Faceted Fossil"] := 77
ITEMS_OF_INTEREST["Fractured Fossil"] := 49.97
ITEMS_OF_INTEREST["Glyphic Fossil"] := 35
ITEMS_OF_INTEREST["Hollow Fossil"] := 11
ITEMS_OF_INTEREST["Prismatic Fossil"] := 6
ITEMS_OF_INTEREST["Perfect Fossil"] := 5
ITEMS_OF_INTEREST["Bound Fossil"] := 5
ITEMS_OF_INTEREST["Corroded Fossil"] := 5
ITEMS_OF_INTEREST["Shuddering Fossil"] := 5
ITEMS_OF_INTEREST["Sanctified Fossil"] := 4
ITEMS_OF_INTEREST["Fundamental Fossil"] := 3
ITEMS_OF_INTEREST["Aetheric Fossil"] := 2
ITEMS_OF_INTEREST["Gilded Fossil"] := 2
ITEMS_OF_INTEREST["Dense Fossil"] := 2
ITEMS_OF_INTEREST["Tangled Fossil"] := 2
ITEMS_OF_INTEREST["Bloodstained Fossil"] := 2
ITEMS_OF_INTEREST["Serrated Fossil"] := 1.5
ITEMS_OF_INTEREST["Deft Fossil"] := 1
ITEMS_OF_INTEREST["Lucent Fossil"] := 0.5
ITEMS_OF_INTEREST["Jagged Fossil"] := 0.48
ITEMS_OF_INTEREST["Frigid Fossil"] := 0.41
ITEMS_OF_INTEREST["Pristine Fossil"] := 0.33
ITEMS_OF_INTEREST["Aberrant Fossil"] := 0.29
ITEMS_OF_INTEREST["Metallic Fossil"] := 0.26
ITEMS_OF_INTEREST["Scorched Fossil"] := 0.25
ITEMS_OF_INTEREST["Prime Chaotic Resonator"] := 25
ITEMS_OF_INTEREST["Powerful Chaotic Resonator"] := 4
ITEMS_OF_INTEREST["Potent Chaotic Resonator"] := 4
ITEMS_OF_INTEREST["Primitive Chaotic Resonator"] := 2.49
ITEMS_OF_INTEREST["Essence of Horror"] := 23
ITEMS_OF_INTEREST["Essence of Delirium"] := 15
ITEMS_OF_INTEREST["Essence of Insanity"] := 14
ITEMS_OF_INTEREST["Essence of Hysteria"] := 13
ITEMS_OF_INTEREST["Deafening Essence of Loathing"] := 8
ITEMS_OF_INTEREST["Deafening Essence of Spite"] := 7
ITEMS_OF_INTEREST["Deafening Essence of Rage"] := 5
ITEMS_OF_INTEREST["Deafening Essence of Sorrow"] := 5
ITEMS_OF_INTEREST["Deafening Essence of Greed"] := 4
ITEMS_OF_INTEREST["Deafening Essence of Scorn"] := 4
ITEMS_OF_INTEREST["Deafening Essence of Anger"] := 3
ITEMS_OF_INTEREST["Deafening Essence of Contempt"] := 3
ITEMS_OF_INTEREST["Deafening Essence of Envy"] := 3
ITEMS_OF_INTEREST["Deafening Essence of Hatred"] := 3
ITEMS_OF_INTEREST["Deafening Essence of Wrath"] := 3
ITEMS_OF_INTEREST["Deafening Essence of Zeal"] := 3
ITEMS_OF_INTEREST["Deafening Essence of Dread"] := 2
ITEMS_OF_INTEREST["Deafening Essence of Fear"] := 2
ITEMS_OF_INTEREST["Deafening Essence of Woe"] := 2
ITEMS_OF_INTEREST["Shrieking Essence of Dread"] := 2
ITEMS_OF_INTEREST["Muttering Essence of Anger"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Fear"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Greed"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Hatred"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Sorrow"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Torment"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Woe"] := 1
ITEMS_OF_INTEREST["Remnant of Corruption"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Dread"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Envy"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Greed"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Loathing"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Rage"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Sorrow"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Spite"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Zeal"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Anger"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Envy"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Fear"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Greed"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Hatred"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Loathing"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Rage"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Scorn"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Sorrow"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Spite"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Woe"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Wrath"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Zeal"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Anger"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Anguish"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Doubt"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Fear"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Greed"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Hatred"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Loathing"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Rage"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Sorrow"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Spite"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Suffering"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Torment"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Woe"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Wrath"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Zeal"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Anger"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Doubt"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Fear"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Greed"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Hatred"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Rage"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Sorrow"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Suffering"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Torment"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Woe"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Wrath"] := 1
ITEMS_OF_INTEREST["Whispering Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Whispering Essence of Greed"] := 1
ITEMS_OF_INTEREST["Whispering Essence of Hatred"] := 1
ITEMS_OF_INTEREST["Whispering Essence of Woe"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Misery"] := 0.97
ITEMS_OF_INTEREST["Screaming Essence of Contempt"] := 0.95
ITEMS_OF_INTEREST["Screaming Essence of Woe"] := 0.9
ITEMS_OF_INTEREST["Screaming Essence of Hatred"] := 0.86
ITEMS_OF_INTEREST["Screaming Essence of Fear"] := 0.85
ITEMS_OF_INTEREST["Screaming Essence of Anger"] := 0.83
ITEMS_OF_INTEREST["Screaming Essence of Torment"] := 0.76
ITEMS_OF_INTEREST["Screaming Essence of Misery"] := 0.69
ITEMS_OF_INTEREST["Screaming Essence of Wrath"] := 0.69
ITEMS_OF_INTEREST["Screaming Essence of Scorn"] := 0.67
ITEMS_OF_INTEREST["Screaming Essence of Doubt"] := 0.65
ITEMS_OF_INTEREST["Shrieking Essence of Anguish"] := 0.57
ITEMS_OF_INTEREST["Deafening Essence of Anguish"] := 0.5
ITEMS_OF_INTEREST["Deafening Essence of Doubt"] := 0.5
ITEMS_OF_INTEREST["Deafening Essence of Misery"] := 0.5
ITEMS_OF_INTEREST["Deafening Essence of Suffering"] := 0.5
ITEMS_OF_INTEREST["Deafening Essence of Torment"] := 0.5
ITEMS_OF_INTEREST["Screaming Essence of Anguish"] := 0.5
ITEMS_OF_INTEREST["Screaming Essence of Suffering"] := 0.5
ITEMS_OF_INTEREST["Shrieking Essence of Doubt"] := 0.5
ITEMS_OF_INTEREST["Shrieking Essence of Suffering"] := 0.5
ITEMS_OF_INTEREST["Shrieking Essence of Torment"] := 0.5
ITEMS_OF_INTEREST["Awakened Enlighten Support"] := 6366.85
ITEMS_OF_INTEREST["Awakened Empower Support"] := 4002.02
ITEMS_OF_INTEREST["Awakened Greater Multiple Projectiles Support"] := 2546.74
ITEMS_OF_INTEREST["Awakened Multistrike Support"] := 2546.74
ITEMS_OF_INTEREST["Awakened Spell Echo Support"] := 1273.37
ITEMS_OF_INTEREST["Divergent Tempest Shield"] := 1182.42
ITEMS_OF_INTEREST["Awakened Enhance Support"] := 782.21
ITEMS_OF_INTEREST["Awakened Elemental Damage with Attacks Support"] := 454.78
ITEMS_OF_INTEREST["Awakened Increased Area of Effect Support"] := 363.82
ITEMS_OF_INTEREST["Anomalous Enlighten Support"] := 363.82
ITEMS_OF_INTEREST["Awakened Fork Support"] := 259.16
ITEMS_OF_INTEREST["Enlighten Support"] := 59
ITEMS_OF_INTEREST["Awakened Elemental Focus Support"] := 254.67
ITEMS_OF_INTEREST["Awakened Chain Support"] := 100
ITEMS_OF_INTEREST["Awakened Burning Damage Support"] := 79.82
ITEMS_OF_INTEREST["Awakened Swift Affliction Support"] := 60
ITEMS_OF_INTEREST["Awakened Generosity Support"] := 15
ITEMS_OF_INTEREST["Awakened Void Manipulation Support"] := 31
ITEMS_OF_INTEREST["Anomalous Empower Support"] := 60.85
ITEMS_OF_INTEREST["Elemental Penetration Support"] := 69
ITEMS_OF_INTEREST["Awakened Unleash Support"] := 58.47
ITEMS_OF_INTEREST["Awakened Cast While Channelling Support"] := 55.71
ITEMS_OF_INTEREST["Awakened Spell Cascade Support"] := 34
ITEMS_OF_INTEREST["Awakened Minion Damage Support"] := 53.55
ITEMS_OF_INTEREST["Empower Support"] := 19.91
ITEMS_OF_INTEREST["Awakened Melee Physical Damage Support"] := 50
ITEMS_OF_INTEREST["Awakened Controlled Destruction Support"] := 45
ITEMS_OF_INTEREST["Awakened Fire Penetration Support"] := 42.67
ITEMS_OF_INTEREST["Awakened Deadly Ailments Support"] := 40
ITEMS_OF_INTEREST["Awakened Melee Splash Support"] := 40
ITEMS_OF_INTEREST["Divergent Ball Lightning"] := 39.8
ITEMS_OF_INTEREST["Awakened Vicious Projectiles Support"] := 37.05
ITEMS_OF_INTEREST["Awakened Added Chaos Damage Support"] := 31.2
ITEMS_OF_INTEREST["Impending Doom Support"] := 29.72
ITEMS_OF_INTEREST["Anomalous Arcane Surge Support"] := 26.63
ITEMS_OF_INTEREST["Anomalous Enhance Support"] := 24.96
ITEMS_OF_INTEREST["Awakened Added Cold Damage Support"] := 20
ITEMS_OF_INTEREST["Awakened Brutality Support"] := 19.9
ITEMS_OF_INTEREST["Divergent Immortal Call"] := 19.69
ITEMS_OF_INTEREST["Divergent Shockwave Totem"] := 19
ITEMS_OF_INTEREST["Awakened Arrow Nova Support"] := 17.34
ITEMS_OF_INTEREST["Enhance Support"] := 17
ITEMS_OF_INTEREST["Divergent Hydrosphere"] := 15
ITEMS_OF_INTEREST["Ritual Splinter"] := 0.0481