ITEMS_OF_INTEREST := {}
ITEMS_OF_INTEREST["Chaos Orb"] := 1
ITEMS_OF_INTEREST["Contract"] := 3
ITEMS_OF_INTEREST["Blueprint"] := 10
ITEMS_OF_INTEREST["Rogue's Marker"] := 0.004
ITEMS_OF_INTEREST["Occupied Map"] := 20
ITEMS_OF_INTEREST["Mirror of Kalandra"] := 72239.85
ITEMS_OF_INTEREST["Mirror Shard"] := 3587.74
ITEMS_OF_INTEREST["Tempering Orb"] := 1039.06
ITEMS_OF_INTEREST["Tailoring Orb"] := 608.88
ITEMS_OF_INTEREST["Secondary Regrading Lens"] := 439.08
ITEMS_OF_INTEREST["Maven's Orb"] := 270.27
ITEMS_OF_INTEREST["Orb of Dominance"] := 265.25
ITEMS_OF_INTEREST["Awakener's Orb"] := 261.76
ITEMS_OF_INTEREST["Exalted Orb"] := 179.97
ITEMS_OF_INTEREST["Hunter's Exalted Orb"] := 139.31
ITEMS_OF_INTEREST["Prime Regrading Lens"] := 91.04
ITEMS_OF_INTEREST["Crusader's Exalted Orb"] := 79.79
ITEMS_OF_INTEREST["Redeemer's Exalted Orb"] := 75.64
ITEMS_OF_INTEREST["Warlord's Exalted Orb"] := 75
ITEMS_OF_INTEREST["Sacred Orb"] := 51.89
ITEMS_OF_INTEREST["Elevated Sextant"] := 36.14
ITEMS_OF_INTEREST["Eldritch Chaos Orb"] := 34.87
ITEMS_OF_INTEREST["Blessing of Chayula"] := 29.78
ITEMS_OF_INTEREST["Eldritch Exalted Orb"] := 25.91
ITEMS_OF_INTEREST["Orb of Conflict"] := 24.85
ITEMS_OF_INTEREST["Eldritch Orb of Annulment"] := 22.15
ITEMS_OF_INTEREST["Exceptional Eldritch Ichor"] := 20.21
ITEMS_OF_INTEREST["Veiled Chaos Orb"] := 16.51
ITEMS_OF_INTEREST["Exceptional Eldritch Ember"] := 14.19
ITEMS_OF_INTEREST["Ancient Orb"] := 11.21
ITEMS_OF_INTEREST["Tainted Blessing"] := 10.89
ITEMS_OF_INTEREST["Jewellery Recombinator"] := 10.65
ITEMS_OF_INTEREST["Comprehensive Scouting Report"] := 10
ITEMS_OF_INTEREST["Blessing of Uul-Netol"] := 8.75
ITEMS_OF_INTEREST["Divine Orb"] := 8.64
ITEMS_OF_INTEREST["Exalted Shard"] := 8.5
ITEMS_OF_INTEREST["Armour Recombinator"] := 8.37
ITEMS_OF_INTEREST["Ritual Vessel"] := 7.74
ITEMS_OF_INTEREST["Blessing of Xoph"] := 7
ITEMS_OF_INTEREST["Blessing of Tul"] := 7
ITEMS_OF_INTEREST["Blessing of Esh"] := 7
ITEMS_OF_INTEREST["Orb of Annulment"] := 6.94
ITEMS_OF_INTEREST["Unstable Catalyst"] := 6.12
ITEMS_OF_INTEREST["Accelerating Catalyst"] := 6
ITEMS_OF_INTEREST["Otherworldly Scouting Report"] := 6
ITEMS_OF_INTEREST["Transforming Power Core"] := 5.88
ITEMS_OF_INTEREST["Weapon Recombinator"] := 5.82
ITEMS_OF_INTEREST["Oil Extractor"] := 5.31
ITEMS_OF_INTEREST["Surveyor's Compass"] := 4.36
ITEMS_OF_INTEREST["Blighted Scouting Report"] := 4
ITEMS_OF_INTEREST["Grand Eldritch Ichor"] := 3.04
ITEMS_OF_INTEREST["Fertile Catalyst"] := 3
ITEMS_OF_INTEREST["Charged Compass"] := 3
ITEMS_OF_INTEREST["Singular Scouting Report"] := 3
ITEMS_OF_INTEREST["Grand Eldritch Ember"] := 2.94
ITEMS_OF_INTEREST["Influenced Scouting Report"] := 2.8
ITEMS_OF_INTEREST["Awakened Sextant"] := 2.72
ITEMS_OF_INTEREST["Infused Engineer's Orb"] := 2
ITEMS_OF_INTEREST["Greater Eldritch Ember"] := 1.99
ITEMS_OF_INTEREST["Operative's Scouting Report"] := 1.98
ITEMS_OF_INTEREST["Stacked Deck"] := 1.9
ITEMS_OF_INTEREST["Orb of Unmaking"] := 1.49
ITEMS_OF_INTEREST["Harbinger's Orb"] := 1.48
ITEMS_OF_INTEREST["Amplifying Power Core"] := 1.46
ITEMS_OF_INTEREST["Delirious Scouting Report"] := 1.12
ITEMS_OF_INTEREST["Greater Eldritch Ichor"] := 1
ITEMS_OF_INTEREST["Tempering Catalyst"] := 0.97
ITEMS_OF_INTEREST["Lesser Eldritch Ember"] := 0.88
ITEMS_OF_INTEREST["Annulment Shard"] := 0.83
ITEMS_OF_INTEREST["Orb of Regret"] := 0.8
ITEMS_OF_INTEREST["Enkindling Orb"] := 0.8
ITEMS_OF_INTEREST["Noxious Catalyst"] := 0.77
ITEMS_OF_INTEREST["Prismatic Catalyst"] := 0.68
ITEMS_OF_INTEREST["Vaal Orb"] := 0.67
ITEMS_OF_INTEREST["Blessed Orb"] := 0.65
ITEMS_OF_INTEREST["Orb of Scouring"] := 0.54
ITEMS_OF_INTEREST["Gemcutter's Prism"] := 0.53
ITEMS_OF_INTEREST["Lesser Eldritch Ichor"] := 0.51
ITEMS_OF_INTEREST["Augmenting Power Core"] := 0.5
ITEMS_OF_INTEREST["Instilling Orb"] := 0.49
ITEMS_OF_INTEREST["Regal Orb"] := 0.38
ITEMS_OF_INTEREST["Intrinsic Catalyst"] := 0.33
ITEMS_OF_INTEREST["Abrasive Catalyst"] := 0.3
ITEMS_OF_INTEREST["Vaal Scouting Report"] := 0.25
ITEMS_OF_INTEREST["Orb of Alchemy"] := 0.24
ITEMS_OF_INTEREST["Orb of Alteration"] := 0.22
ITEMS_OF_INTEREST["Glassblower's Bauble"] := 0.22
ITEMS_OF_INTEREST["Power Core"] := 0.21
ITEMS_OF_INTEREST["Orb of Horizons"] := 0.2
ITEMS_OF_INTEREST["Orb of Fusing"] := 0.19
ITEMS_OF_INTEREST["Explorer's Scouting Report"] := 0.19
ITEMS_OF_INTEREST["Turbulent Catalyst"] := 0.17
ITEMS_OF_INTEREST["Imbued Catalyst"] := 0.14
ITEMS_OF_INTEREST["Orb of Binding"] := 0.11
ITEMS_OF_INTEREST["Chromatic Orb"] := 0.09
ITEMS_OF_INTEREST["Orb of Chance"] := 0.08
ITEMS_OF_INTEREST["Cartographer's Chisel"] := 0.07
ITEMS_OF_INTEREST["Orb of Augmentation"] := 0.07
ITEMS_OF_INTEREST["Jeweller's Orb"] := 0.05
ITEMS_OF_INTEREST["Engineer's Orb"] := 0.05
ITEMS_OF_INTEREST["Blacksmith's Whetstone"] := 0.03
ITEMS_OF_INTEREST["Orb of Transmutation"] := 0.02
ITEMS_OF_INTEREST["Portal Scroll"] := 0.01
ITEMS_OF_INTEREST["Armourer's Scrap"] := 0.01
ITEMS_OF_INTEREST["Uul-Netol's Flawless Breachstone"] := 359.75
ITEMS_OF_INTEREST["Chayula's Flawless Breachstone"] := 176.9
ITEMS_OF_INTEREST["Chayula's Pure Breachstone"] := 128.27
ITEMS_OF_INTEREST["Xoph's Flawless Breachstone"] := 110.71
ITEMS_OF_INTEREST["Tul's Flawless Breachstone"] := 110.71
ITEMS_OF_INTEREST["Esh's Flawless Breachstone"] := 110.71
ITEMS_OF_INTEREST["The Maven's Writ"] := 94.81
ITEMS_OF_INTEREST["Fragment of Shape"] := 90.05
ITEMS_OF_INTEREST["Timeless Maraketh Emblem"] := 89.61
ITEMS_OF_INTEREST["Fragment of Knowledge"] := 89.34
ITEMS_OF_INTEREST["Unrelenting Timeless Maraketh Emblem"] := 69.98
ITEMS_OF_INTEREST["Uul-Netol's Pure Breachstone"] := 69.55
ITEMS_OF_INTEREST["Gift to the Goddess"] := 69.4
ITEMS_OF_INTEREST["Unrelenting Timeless Karui Emblem"] := 59.99
ITEMS_OF_INTEREST["Unrelenting Timeless Eternal Emblem"] := 59.99
ITEMS_OF_INTEREST["Unrelenting Timeless Templar Emblem"] := 59.99
ITEMS_OF_INTEREST["Unrelenting Timeless Vaal Emblem"] := 59.99
ITEMS_OF_INTEREST["Uul-Netol's Enriched Breachstone"] := 59.89
ITEMS_OF_INTEREST["Chayula's Enriched Breachstone"] := 49.59
ITEMS_OF_INTEREST["Chayula's Charged Breachstone"] := 44.38
ITEMS_OF_INTEREST["Chayula's Breachstone"] := 44.22
ITEMS_OF_INTEREST["Xoph's Pure Breachstone"] := 40.56
ITEMS_OF_INTEREST["Tul's Pure Breachstone"] := 40.56
ITEMS_OF_INTEREST["Esh's Pure Breachstone"] := 40.56
ITEMS_OF_INTEREST["Simulacrum"] := 37.7
ITEMS_OF_INTEREST["Fragment of Terror"] := 30.22
ITEMS_OF_INTEREST["Fragment of Emptiness"] := 29.54
ITEMS_OF_INTEREST["Uul-Netol's Charged Breachstone"] := 29.33
ITEMS_OF_INTEREST["Timeless Templar Emblem"] := 23.41
ITEMS_OF_INTEREST["Fragment of Eradication"] := 21.23
ITEMS_OF_INTEREST["Esh's Enriched Breachstone"] := 20.79
ITEMS_OF_INTEREST["Fragment of Enslavement"] := 19.3
ITEMS_OF_INTEREST["Uul-Netol's Breachstone"] := 18.69
ITEMS_OF_INTEREST["Tul's Enriched Breachstone"] := 18.24
ITEMS_OF_INTEREST["Xoph's Enriched Breachstone"] := 17.34
ITEMS_OF_INTEREST["Fragment of Purification"] := 16.86
ITEMS_OF_INTEREST["Fragment of Constriction"] := 16.75
ITEMS_OF_INTEREST["Fragment of the Chimera"] := 13.85
ITEMS_OF_INTEREST["Fragment of the Minotaur"] := 13.82
ITEMS_OF_INTEREST["Fragment of the Hydra"] := 12.87
ITEMS_OF_INTEREST["Al-Hezmin's Crest"] := 12.81
ITEMS_OF_INTEREST["Veritania's Crest"] := 12.81
ITEMS_OF_INTEREST["Baran's Crest"] := 12.56
ITEMS_OF_INTEREST["Drox's Crest"] := 11.84
ITEMS_OF_INTEREST["Xoph's Breachstone"] := 11.08
ITEMS_OF_INTEREST["Tul's Breachstone"] := 11.08
ITEMS_OF_INTEREST["Xoph's Charged Breachstone"] := 11
ITEMS_OF_INTEREST["Tul's Charged Breachstone"] := 11
ITEMS_OF_INTEREST["Esh's Charged Breachstone"] := 11
ITEMS_OF_INTEREST["Esh's Breachstone"] := 10.1
ITEMS_OF_INTEREST["Crescent Splinter"] := 9.53
ITEMS_OF_INTEREST["Mortal Ignorance"] := 8.73
ITEMS_OF_INTEREST["Fragment of the Phoenix"] := 7.43
ITEMS_OF_INTEREST["Timeless Vaal Emblem"] := 6
ITEMS_OF_INTEREST["Dedication to the Goddess"] := 5.58
ITEMS_OF_INTEREST["Timeless Karui Emblem"] := 5.44
ITEMS_OF_INTEREST["Timeless Eternal Emblem"] := 5.44
ITEMS_OF_INTEREST["Mortal Rage"] := 3
ITEMS_OF_INTEREST["Mortal Hope"] := 2.43
ITEMS_OF_INTEREST["Tribute to the Goddess"] := 1.82
ITEMS_OF_INTEREST["Divine Vessel"] := 1.5
ITEMS_OF_INTEREST["Mortal Grief"] := 1
ITEMS_OF_INTEREST["Timeless Maraketh Splinter"] := 0.75
ITEMS_OF_INTEREST["Offering to the Goddess"] := 0.56
ITEMS_OF_INTEREST["Splinter of Uul-Netol"] := 0.37
ITEMS_OF_INTEREST["Splinter of Chayula"] := 0.3
ITEMS_OF_INTEREST["Timeless Vaal Splinter"] := 0.25
ITEMS_OF_INTEREST["Timeless Templar Splinter"] := 0.2
ITEMS_OF_INTEREST["Splinter of Tul"] := 0.17
ITEMS_OF_INTEREST["Splinter of Esh"] := 0.17
ITEMS_OF_INTEREST["Splinter of Xoph"] := 0.16
ITEMS_OF_INTEREST["Simulacrum Splinter"] := 0.12
ITEMS_OF_INTEREST["Sacrifice at Midnight"] := 0.1
ITEMS_OF_INTEREST["Sacrifice at Dawn"] := 0.1
ITEMS_OF_INTEREST["Sacrifice at Noon"] := 0.1
ITEMS_OF_INTEREST["Sacrifice at Dusk"] := 0.09
ITEMS_OF_INTEREST["Timeless Karui Splinter"] := 0.05
ITEMS_OF_INTEREST["Timeless Eternal Empire Splinter"] := 0.04
ITEMS_OF_INTEREST["Tainted Oil"] := 179.69
ITEMS_OF_INTEREST["Golden Oil"] := 41.04
ITEMS_OF_INTEREST["Silver Oil"] := 17
ITEMS_OF_INTEREST["Opalescent Oil"] := 7.89
ITEMS_OF_INTEREST["Black Oil"] := 2.5
ITEMS_OF_INTEREST["Crimson Oil"] := 2
ITEMS_OF_INTEREST["Violet Oil"] := 1
ITEMS_OF_INTEREST["Verdant Oil"] := 0.5
ITEMS_OF_INTEREST["Teal Oil"] := 0.5
ITEMS_OF_INTEREST["Amber Oil"] := 0.5
ITEMS_OF_INTEREST["Azure Oil"] := 0.5
ITEMS_OF_INTEREST["Indigo Oil"] := 0.5
ITEMS_OF_INTEREST["Sepia Oil"] := 0.3
ITEMS_OF_INTEREST["Clear Oil"] := 0.3
ITEMS_OF_INTEREST["Foreboding Incubator"] := 8.08
ITEMS_OF_INTEREST["Geomancer's Incubator"] := 5.04
ITEMS_OF_INTEREST["Ornate Incubator"] := 5
ITEMS_OF_INTEREST["Skittering Incubator"] := 5
ITEMS_OF_INTEREST["Time-Lost Incubator"] := 5
ITEMS_OF_INTEREST["Thaumaturge's Incubator"] := 5
ITEMS_OF_INTEREST["Kalguuran Incubator"] := 5
ITEMS_OF_INTEREST["Diviner's Incubator"] := 4.16
ITEMS_OF_INTEREST["Celestial Jeweller's Incubator"] := 4
ITEMS_OF_INTEREST["Celestial Blacksmith's Incubator"] := 4
ITEMS_OF_INTEREST["Morphing Incubator"] := 4
ITEMS_OF_INTEREST["Maddening Incubator"] := 4
ITEMS_OF_INTEREST["Fragmented Incubator"] := 3.17
ITEMS_OF_INTEREST["Primal Incubator"] := 3
ITEMS_OF_INTEREST["Enchanted Incubator"] := 3
ITEMS_OF_INTEREST["Celestial Armoursmith's Incubator"] := 3
ITEMS_OF_INTEREST["Otherworldly Incubator"] := 3
ITEMS_OF_INTEREST["Obscured Incubator"] := 3
ITEMS_OF_INTEREST["Infused Incubator"] := 3
ITEMS_OF_INTEREST["Blighted Incubator"] := 3
ITEMS_OF_INTEREST["Cartographer's Incubator"] := 2.65
ITEMS_OF_INTEREST["Singular Incubator"] := 2
ITEMS_OF_INTEREST["Fossilised Incubator"] := 2
ITEMS_OF_INTEREST["Mysterious Incubator"] := 2
ITEMS_OF_INTEREST["Abyssal Incubator"] := 1.71
ITEMS_OF_INTEREST["Maze of the Minotaur Map"] := 12
ITEMS_OF_INTEREST["Forge of the Phoenix Map"] := 11.81
ITEMS_OF_INTEREST["Crimson Temple Map"] := 1
ITEMS_OF_INTEREST["Carcass Map"] := 1
ITEMS_OF_INTEREST["Lair of the Hydra Map"] := 10
ITEMS_OF_INTEREST["Pit of the Chimera Map"] := 7.84
ITEMS_OF_INTEREST["City Square Map"] := 1.66
ITEMS_OF_INTEREST["Vaal Temple Map"] := 5.82
ITEMS_OF_INTEREST["Beach Map"] := 4.47
ITEMS_OF_INTEREST["Promenade Map"] := 2
ITEMS_OF_INTEREST["Cemetery Map"] := 1
ITEMS_OF_INTEREST["Tropical Island Map"] := 1
ITEMS_OF_INTEREST["Overgrown Shrine Map"] := 1
ITEMS_OF_INTEREST["Toxic Sewer Map"] := 1.24
ITEMS_OF_INTEREST["Waste Pool Map"] := 2
ITEMS_OF_INTEREST["Tower Map"] := 1
ITEMS_OF_INTEREST["Bone Crypt Map"] := 1
ITEMS_OF_INTEREST["Alleyways Map"] := 4
ITEMS_OF_INTEREST["Mesa Map"] := 1.34
ITEMS_OF_INTEREST["Ashen Wood Map"] := 1
ITEMS_OF_INTEREST["Core Map"] := 2
ITEMS_OF_INTEREST["Caldera Map"] := 4.94
ITEMS_OF_INTEREST["Arsenal Map"] := 1
ITEMS_OF_INTEREST["Courtyard Map"] := 1
ITEMS_OF_INTEREST["Reef Map"] := 1
ITEMS_OF_INTEREST["Glacier Map"] := 4
ITEMS_OF_INTEREST["Atoll Map"] := 2
ITEMS_OF_INTEREST["Wharf Map"] := 2
ITEMS_OF_INTEREST["Strand Map"] := 4.11
ITEMS_OF_INTEREST["Fields Map"] := 4
ITEMS_OF_INTEREST["Basilica Map"] := 1
ITEMS_OF_INTEREST["Cells Map"] := 4
ITEMS_OF_INTEREST["Dunes Map"] := 1
ITEMS_OF_INTEREST["Infested Valley Map"] := 1
ITEMS_OF_INTEREST["Palace Map"] := 3.18
ITEMS_OF_INTEREST["Shore Map"] := 1
ITEMS_OF_INTEREST["Residence Map"] := 4
ITEMS_OF_INTEREST["Lava Lake Map"] := 4
ITEMS_OF_INTEREST["Cursed Crypt Map"] := 4
ITEMS_OF_INTEREST["Fungal Hollow Map"] := 4
ITEMS_OF_INTEREST["Park Map"] := 4
ITEMS_OF_INTEREST["Barrows Map"] := 4
ITEMS_OF_INTEREST["Ramparts Map"] := 1
ITEMS_OF_INTEREST["Port Map"] := 2
ITEMS_OF_INTEREST["Vaal Pyramid Map"] := 2
ITEMS_OF_INTEREST["Acid Caverns Map"] := 1
ITEMS_OF_INTEREST["Underground Sea Map"] := 1
ITEMS_OF_INTEREST["Frozen Cabins Map"] := 1
ITEMS_OF_INTEREST["Villa Map"] := 2
ITEMS_OF_INTEREST["Crystal Ore Map"] := 1
ITEMS_OF_INTEREST["Summit Map"] := 2
ITEMS_OF_INTEREST["Underground River Map"] := 2
ITEMS_OF_INTEREST["Dark Forest Map"] := 4
ITEMS_OF_INTEREST["Temple Map"] := 1
ITEMS_OF_INTEREST["Jungle Valley Map"] := 2
ITEMS_OF_INTEREST["Coral Ruins Map"] := 4
ITEMS_OF_INTEREST["Cage Map"] := 2
ITEMS_OF_INTEREST["Mineral Pools Map"] := 2
ITEMS_OF_INTEREST["Precinct Map"] := 2
ITEMS_OF_INTEREST["Foundry Map"] := 4
ITEMS_OF_INTEREST["Grave Trough Map"] := 4
ITEMS_OF_INTEREST["Orchard Map"] := 1
ITEMS_OF_INTEREST["Desert Map"] := 1
ITEMS_OF_INTEREST["Thicket Map"] := 1
ITEMS_OF_INTEREST["Sepulchre Map"] := 1
ITEMS_OF_INTEREST["Desert Spring Map"] := 1
ITEMS_OF_INTEREST["Ivory Temple Map"] := 1
ITEMS_OF_INTEREST["Lava Chamber Map"] := 1
ITEMS_OF_INTEREST["Pit Map"] := 4
ITEMS_OF_INTEREST["Factory Map"] := 2
ITEMS_OF_INTEREST["Grotto Map"] := 1
ITEMS_OF_INTEREST["Lookout Map"] := 1
ITEMS_OF_INTEREST["Colonnade Map"] := 1
ITEMS_OF_INTEREST["Bazaar Map"] := 1
ITEMS_OF_INTEREST["Laboratory Map"] := 2
ITEMS_OF_INTEREST["Sunken City Map"] := 2
ITEMS_OF_INTEREST["Mausoleum Map"] := 1
ITEMS_OF_INTEREST["Arcade Map"] := 1
ITEMS_OF_INTEREST["Moon Temple Map"] := 1
ITEMS_OF_INTEREST["Necropolis Map"] := 1
ITEMS_OF_INTEREST["Plaza Map"] := 1
ITEMS_OF_INTEREST["Primordial Pool Map"] := 1
ITEMS_OF_INTEREST["Mud Geyser Map"] := 1
ITEMS_OF_INTEREST["Canyon Map"] := 1
ITEMS_OF_INTEREST["Bramble Valley Map"] := 1
ITEMS_OF_INTEREST["Volcano Map"] := 1
ITEMS_OF_INTEREST["Peninsula Map"] := 0.94
ITEMS_OF_INTEREST["Armoury Map"] := 1
ITEMS_OF_INTEREST["Cold River Map"] := 1
ITEMS_OF_INTEREST["Gardens Map"] := 1
ITEMS_OF_INTEREST["Crimson Township Map"] := 1
ITEMS_OF_INTEREST["Lair Map"] := 1
ITEMS_OF_INTEREST["Dungeon Map"] := 1.12
ITEMS_OF_INTEREST["Bog Map"] := 1
ITEMS_OF_INTEREST["Arid Lake Map"] := 0.81
ITEMS_OF_INTEREST["Spider Forest Map"] := 1
ITEMS_OF_INTEREST["Dry Sea Map"] := 1
ITEMS_OF_INTEREST["Wasteland Map"] := 2
ITEMS_OF_INTEREST["Museum Map"] := 1
ITEMS_OF_INTEREST["Burial Chambers Map"] := 3.62
ITEMS_OF_INTEREST["Terrace Map"] := 1
ITEMS_OF_INTEREST["Overgrown Ruin Map"] := 2
ITEMS_OF_INTEREST["Maze Map"] := 1
ITEMS_OF_INTEREST["Marshes Map"] := 1
ITEMS_OF_INTEREST["Arena Map"] := 1
ITEMS_OF_INTEREST["Blighted Beach Map"] := 15
ITEMS_OF_INTEREST["Blighted Crimson Township Map"] := 7
ITEMS_OF_INTEREST["Blighted Strand Map"] := 15
ITEMS_OF_INTEREST["Blighted Alleyways Map"] := 15
ITEMS_OF_INTEREST["Blighted Overgrown Shrine Map"] := 6
ITEMS_OF_INTEREST["Blighted Courtyard Map"] := 7
ITEMS_OF_INTEREST["Blighted Moon Temple Map"] := 6.17
ITEMS_OF_INTEREST["Blighted Ramparts Map"] := 5.88
ITEMS_OF_INTEREST["Blighted Villa Map"] := 10
ITEMS_OF_INTEREST["Blighted Cold River Map"] := 6
ITEMS_OF_INTEREST["Blighted Peninsula Map"] := 6
ITEMS_OF_INTEREST["Blighted Ashen Wood Map"] := 6.59
ITEMS_OF_INTEREST["Blighted Armoury Map"] := 6.86
ITEMS_OF_INTEREST["Blighted Pit Map"] := 10
ITEMS_OF_INTEREST["Blighted Cells Map"] := 15
ITEMS_OF_INTEREST["Blighted Caldera Map"] := 21
ITEMS_OF_INTEREST["Blighted Burial Chambers Map"] := 21
ITEMS_OF_INTEREST["Blighted Canyon Map"] := 9.47
ITEMS_OF_INTEREST["Blighted Mineral Pools Map"] := 10
ITEMS_OF_INTEREST["Blighted Bazaar Map"] := 8
ITEMS_OF_INTEREST["Blighted Spider Forest Map"] := 5.66
ITEMS_OF_INTEREST["Blighted Arid Lake Map"] := 6.36
ITEMS_OF_INTEREST["Blighted Mud Geyser Map"] := 7
ITEMS_OF_INTEREST["Blighted Underground Sea Map"] := 6
ITEMS_OF_INTEREST["Blighted Lava Chamber Map"] := 15
ITEMS_OF_INTEREST["Blighted City Square Map"] := 7
ITEMS_OF_INTEREST["Blighted Marshes Map"] := 10
ITEMS_OF_INTEREST["Blighted Acid Caverns Map"] := 6.88
ITEMS_OF_INTEREST["Blighted Arsenal Map"] := 7.18
ITEMS_OF_INTEREST["Blighted Summit Map"] := 7
ITEMS_OF_INTEREST["Blighted Dunes Map"] := 13.61
ITEMS_OF_INTEREST["Blighted Foundry Map"] := 10
ITEMS_OF_INTEREST["Blighted Waste Pool Map"] := 10
ITEMS_OF_INTEREST["Blighted Lava Lake Map"] := 20
ITEMS_OF_INTEREST["Blighted Laboratory Map"] := 11
ITEMS_OF_INTEREST["Blighted Cage Map"] := 9.77
ITEMS_OF_INTEREST["Blighted Park Map"] := 17
ITEMS_OF_INTEREST["Blighted Volcano Map"] := 6.98
ITEMS_OF_INTEREST["Blighted Port Map"] := 10
ITEMS_OF_INTEREST["Blighted Ivory Temple Map"] := 7
ITEMS_OF_INTEREST["Blighted Promenade Map"] := 8
ITEMS_OF_INTEREST["Blighted Grave Trough Map"] := 10
ITEMS_OF_INTEREST["Blighted Wasteland Map"] := 11
ITEMS_OF_INTEREST["Blighted Underground River Map"] := 10
ITEMS_OF_INTEREST["Blighted Fields Map"] := 14
ITEMS_OF_INTEREST["Blighted Cursed Crypt Map"] := 15
ITEMS_OF_INTEREST["Blighted Glacier Map"] := 8
ITEMS_OF_INTEREST["Blighted Tropical Island Map"] := 7
ITEMS_OF_INTEREST["Blighted Mausoleum Map"] := 9
ITEMS_OF_INTEREST["Blighted Crimson Temple Map"] := 9.6
ITEMS_OF_INTEREST["Blighted Temple Map"] := 6.38
ITEMS_OF_INTEREST["Blighted Cemetery Map"] := 6.96
ITEMS_OF_INTEREST["Blighted Bramble Valley Map"] := 7
ITEMS_OF_INTEREST["Blighted Orchard Map"] := 6.37
ITEMS_OF_INTEREST["Blighted Barrows Map"] := 15.69
ITEMS_OF_INTEREST["Blighted Dry Sea Map"] := 9
ITEMS_OF_INTEREST["Blighted Lookout Map"] := 7
ITEMS_OF_INTEREST["Blighted Wharf Map"] := 10
ITEMS_OF_INTEREST["Blighted Toxic Sewer Map"] := 10
ITEMS_OF_INTEREST["Blighted Dark Forest Map"] := 10
ITEMS_OF_INTEREST["Blighted Mesa Map"] := 7
ITEMS_OF_INTEREST["Blighted Colonnade Map"] := 7
ITEMS_OF_INTEREST["Blighted Infested Valley Map"] := 6
ITEMS_OF_INTEREST["Blighted Lair Map"] := 12
ITEMS_OF_INTEREST["Blighted Gardens Map"] := 8
ITEMS_OF_INTEREST["Blighted Dungeon Map"] := 5.48
ITEMS_OF_INTEREST["Blighted Desert Spring Map"] := 7
ITEMS_OF_INTEREST["Blighted Sepulchre Map"] := 7
ITEMS_OF_INTEREST["Blighted Basilica Map"] := 6
ITEMS_OF_INTEREST["Blighted Necropolis Map"] := 6
ITEMS_OF_INTEREST["Blighted Precinct Map"] := 10
ITEMS_OF_INTEREST["Blighted Jungle Valley Map"] := 8.51
ITEMS_OF_INTEREST["Blighted Plaza Map"] := 6
ITEMS_OF_INTEREST["Blighted Thicket Map"] := 8
ITEMS_OF_INTEREST["Blighted Coral Ruins Map"] := 10.7
ITEMS_OF_INTEREST["Blighted Museum Map"] := 6
ITEMS_OF_INTEREST["Blighted Primordial Pool Map"] := 7
ITEMS_OF_INTEREST["Blighted Tower Map"] := 6
ITEMS_OF_INTEREST["Blighted Bog Map"] := 6
ITEMS_OF_INTEREST["Blighted Palace Map"] := 15.76
ITEMS_OF_INTEREST["Blighted Reef Map"] := 7
ITEMS_OF_INTEREST["Blighted Arcade Map"] := 5.64
ITEMS_OF_INTEREST["Blighted Atoll Map"] := 7.91
ITEMS_OF_INTEREST["Blighted Desert Map"] := 8
ITEMS_OF_INTEREST["Blighted Bone Crypt Map"] := 7
ITEMS_OF_INTEREST["Blighted Shore Map"] := 10.08
ITEMS_OF_INTEREST["Doryani's Machinarium"] := 508.23
ITEMS_OF_INTEREST["Cortex"] := 399.32
ITEMS_OF_INTEREST["Replica Cortex"] := 361.09
ITEMS_OF_INTEREST["Augmented Distant Memory"] := 50
ITEMS_OF_INTEREST["Altered Distant Memory"] := 50
ITEMS_OF_INTEREST["Twisted Distant Memory"] := 50
ITEMS_OF_INTEREST["Rewritten Distant Memory"] := 50
ITEMS_OF_INTEREST["The Vinktar Square"] := 45
ITEMS_OF_INTEREST["Infused Beachhead"] := 28.69
ITEMS_OF_INTEREST["Replica Poorjoy's Asylum"] := 24.18
ITEMS_OF_INTEREST["The Coward's Trial"] := 21
ITEMS_OF_INTEREST["The Putrid Cloister"] := 10
ITEMS_OF_INTEREST["The Beachhead"] := 10
ITEMS_OF_INTEREST["The Twilight Temple"] := 6
ITEMS_OF_INTEREST["Mao Kun"] := 4
ITEMS_OF_INTEREST["Poorjoy's Asylum"] := 5
ITEMS_OF_INTEREST["Replica Pillars of Arun"] := 5
ITEMS_OF_INTEREST["Caer Blaidd, Wolfpack's Den"] := 4
ITEMS_OF_INTEREST["Hallowed Ground"] := 4
ITEMS_OF_INTEREST["Death and Taxes"] := 4
ITEMS_OF_INTEREST["Vaults of Atziri"] := 3
ITEMS_OF_INTEREST["Hall of Grandmasters"] := 1
ITEMS_OF_INTEREST["Oba's Cursed Trove"] := 1.5
ITEMS_OF_INTEREST["Acton's Nightmare"] := 1.49
ITEMS_OF_INTEREST["Pillars of Arun"] := 2
ITEMS_OF_INTEREST["Maelström of Chaos"] := 1
ITEMS_OF_INTEREST["Whakawairua Tuahu"] := 2
ITEMS_OF_INTEREST["Olmec's Sanctum"] := 1.99
ITEMS_OF_INTEREST["Skittering Delirium Orb"] := 50
ITEMS_OF_INTEREST["Diviner's Delirium Orb"] := 35
ITEMS_OF_INTEREST["Cartographer's Delirium Orb"] := 21
ITEMS_OF_INTEREST["Fine Delirium Orb"] := 21
ITEMS_OF_INTEREST["Foreboding Delirium Orb"] := 19.1
ITEMS_OF_INTEREST["Singular Delirium Orb"] := 15
ITEMS_OF_INTEREST["Armoursmith's Delirium Orb"] := 15
ITEMS_OF_INTEREST["Jeweller's Delirium Orb"] := 13
ITEMS_OF_INTEREST["Fragmented Delirium Orb"] := 12
ITEMS_OF_INTEREST["Obscured Delirium Orb"] := 12
ITEMS_OF_INTEREST["Fossilised Delirium Orb"] := 12
ITEMS_OF_INTEREST["Thaumaturge's Delirium Orb"] := 12
ITEMS_OF_INTEREST["Amorphous Delirium Orb"] := 12
ITEMS_OF_INTEREST["Timeless Delirium Orb"] := 11.67
ITEMS_OF_INTEREST["Blacksmith's Delirium Orb"] := 11.66
ITEMS_OF_INTEREST["Imperial Delirium Orb"] := 11
ITEMS_OF_INTEREST["Abyssal Delirium Orb"] := 11
ITEMS_OF_INTEREST["Blighted Delirium Orb"] := 11
ITEMS_OF_INTEREST["Whispering Delirium Orb"] := 11
ITEMS_OF_INTEREST["Winged Divination Scarab"] := 81.01
ITEMS_OF_INTEREST["Winged Reliquary Scarab"] := 80
ITEMS_OF_INTEREST["Winged Harbinger Scarab"] := 69
ITEMS_OF_INTEREST["Winged Abyss Scarab"] := 67
ITEMS_OF_INTEREST["Winged Ambush Scarab"] := 60.07
ITEMS_OF_INTEREST["Winged Breach Scarab"] := 39
ITEMS_OF_INTEREST["Gilded Divination Scarab"] := 28
ITEMS_OF_INTEREST["Craicic Lure"] := 24
ITEMS_OF_INTEREST["Winged Expedition Scarab"] := 20
ITEMS_OF_INTEREST["Winged Legion Scarab"] := 16
ITEMS_OF_INTEREST["Gilded Ambush Scarab"] := 15
ITEMS_OF_INTEREST["Winged Sulphite Scarab"] := 13
ITEMS_OF_INTEREST["Winged Cartography Scarab"] := 13
ITEMS_OF_INTEREST["Winged Torment Scarab"] := 13
ITEMS_OF_INTEREST["Winged Blight Scarab"] := 13
ITEMS_OF_INTEREST["Winged Bestiary Scarab"] := 12.96
ITEMS_OF_INTEREST["Winged Elder Scarab"] := 12.33
ITEMS_OF_INTEREST["Gilded Reliquary Scarab"] := 12
ITEMS_OF_INTEREST["Winged Metamorph Scarab"] := 12
ITEMS_OF_INTEREST["Winged Shaper Scarab"] := 12
ITEMS_OF_INTEREST["Gilded Expedition Scarab"] := 12
ITEMS_OF_INTEREST["Gilded Harbinger Scarab"] := 11.29
ITEMS_OF_INTEREST["Fenumal Lure"] := 10
ITEMS_OF_INTEREST["Polished Divination Scarab"] := 9
ITEMS_OF_INTEREST["Gilded Abyss Scarab"] := 8
ITEMS_OF_INTEREST["Polished Ambush Scarab"] := 7
ITEMS_OF_INTEREST["Gilded Breach Scarab"] := 6
ITEMS_OF_INTEREST["Polished Expedition Scarab"] := 6
ITEMS_OF_INTEREST["Polished Harbinger Scarab"] := 5
ITEMS_OF_INTEREST["Gilded Legion Scarab"] := 5
ITEMS_OF_INTEREST["Saqawine Lure"] := 5
ITEMS_OF_INTEREST["Gilded Blight Scarab"] := 5
ITEMS_OF_INTEREST["Farric Lure"] := 4
ITEMS_OF_INTEREST["Rusted Ambush Scarab"] := 3.56
ITEMS_OF_INTEREST["Gilded Cartography Scarab"] := 3
ITEMS_OF_INTEREST["Rusted Divination Scarab"] := 2.72
ITEMS_OF_INTEREST["Polished Cartography Scarab"] := 2
ITEMS_OF_INTEREST["Gilded Bestiary Scarab"] := 2
ITEMS_OF_INTEREST["Gilded Sulphite Scarab"] := 2
ITEMS_OF_INTEREST["Rusted Expedition Scarab"] := 2
ITEMS_OF_INTEREST["Rusted Harbinger Scarab"] := 1.94
ITEMS_OF_INTEREST["Polished Breach Scarab"] := 1.5
ITEMS_OF_INTEREST["Gilded Elder Scarab"] := 1.5
ITEMS_OF_INTEREST["Rusted Cartography Scarab"] := 1
ITEMS_OF_INTEREST["Rusted Elder Scarab"] := 1
ITEMS_OF_INTEREST["Gilded Torment Scarab"] := 1
ITEMS_OF_INTEREST["Gilded Shaper Scarab"] := 1
ITEMS_OF_INTEREST["Polished Elder Scarab"] := 1
ITEMS_OF_INTEREST["Polished Bestiary Scarab"] := 1
ITEMS_OF_INTEREST["Polished Reliquary Scarab"] := 1
ITEMS_OF_INTEREST["Polished Legion Scarab"] := 1
ITEMS_OF_INTEREST["Gilded Metamorph Scarab"] := 1
ITEMS_OF_INTEREST["Polished Abyss Scarab"] := 1
ITEMS_OF_INTEREST["Polished Blight Scarab"] := 1
ITEMS_OF_INTEREST["Rusted Reliquary Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Bestiary Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Torment Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Breach Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Shaper Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Sulphite Scarab"] := 0.5
ITEMS_OF_INTEREST["Polished Shaper Scarab"] := 0.5
ITEMS_OF_INTEREST["Polished Sulphite Scarab"] := 0.5
ITEMS_OF_INTEREST["Polished Torment Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Legion Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Metamorph Scarab"] := 0.5
ITEMS_OF_INTEREST["Polished Metamorph Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Blight Scarab"] := 0.5
ITEMS_OF_INTEREST["Rusted Abyss Scarab"] := 0.5
ITEMS_OF_INTEREST["Faceted Fossil"] := 75
ITEMS_OF_INTEREST["Fractured Fossil"] := 50
ITEMS_OF_INTEREST["Glyphic Fossil"] := 29
ITEMS_OF_INTEREST["Hollow Fossil"] := 10
ITEMS_OF_INTEREST["Prismatic Fossil"] := 6.77
ITEMS_OF_INTEREST["Perfect Fossil"] := 5
ITEMS_OF_INTEREST["Bound Fossil"] := 5
ITEMS_OF_INTEREST["Shuddering Fossil"] := 5
ITEMS_OF_INTEREST["Sanctified Fossil"] := 4.48
ITEMS_OF_INTEREST["Corroded Fossil"] := 4.46
ITEMS_OF_INTEREST["Gilded Fossil"] := 2
ITEMS_OF_INTEREST["Dense Fossil"] := 2
ITEMS_OF_INTEREST["Serrated Fossil"] := 2
ITEMS_OF_INTEREST["Tangled Fossil"] := 2
ITEMS_OF_INTEREST["Bloodstained Fossil"] := 2
ITEMS_OF_INTEREST["Fundamental Fossil"] := 2
ITEMS_OF_INTEREST["Aetheric Fossil"] := 1.5
ITEMS_OF_INTEREST["Deft Fossil"] := 1.5
ITEMS_OF_INTEREST["Jagged Fossil"] := 0.5
ITEMS_OF_INTEREST["Frigid Fossil"] := 0.5
ITEMS_OF_INTEREST["Pristine Fossil"] := 0.5
ITEMS_OF_INTEREST["Lucent Fossil"] := 0.5
ITEMS_OF_INTEREST["Aberrant Fossil"] := 0.48
ITEMS_OF_INTEREST["Metallic Fossil"] := 0.4
ITEMS_OF_INTEREST["Scorched Fossil"] := 0.31
ITEMS_OF_INTEREST["Prime Chaotic Resonator"] := 24
ITEMS_OF_INTEREST["Powerful Chaotic Resonator"] := 4
ITEMS_OF_INTEREST["Potent Chaotic Resonator"] := 4
ITEMS_OF_INTEREST["Primitive Chaotic Resonator"] := 2.07
ITEMS_OF_INTEREST["Essence of Horror"] := 24
ITEMS_OF_INTEREST["Essence of Delirium"] := 17
ITEMS_OF_INTEREST["Essence of Insanity"] := 15
ITEMS_OF_INTEREST["Essence of Hysteria"] := 14
ITEMS_OF_INTEREST["Deafening Essence of Loathing"] := 7
ITEMS_OF_INTEREST["Deafening Essence of Sorrow"] := 6
ITEMS_OF_INTEREST["Deafening Essence of Spite"] := 5.75
ITEMS_OF_INTEREST["Deafening Essence of Rage"] := 5
ITEMS_OF_INTEREST["Deafening Essence of Envy"] := 3
ITEMS_OF_INTEREST["Deafening Essence of Greed"] := 3
ITEMS_OF_INTEREST["Deafening Essence of Scorn"] := 3
ITEMS_OF_INTEREST["Deafening Essence of Zeal"] := 3
ITEMS_OF_INTEREST["Deafening Essence of Anger"] := 2.08
ITEMS_OF_INTEREST["Deafening Essence of Contempt"] := 2
ITEMS_OF_INTEREST["Deafening Essence of Dread"] := 2
ITEMS_OF_INTEREST["Deafening Essence of Hatred"] := 2
ITEMS_OF_INTEREST["Deafening Essence of Woe"] := 2
ITEMS_OF_INTEREST["Deafening Essence of Wrath"] := 2
ITEMS_OF_INTEREST["Shrieking Essence of Dread"] := 2
ITEMS_OF_INTEREST["Shrieking Essence of Greed"] := 1.87
ITEMS_OF_INTEREST["Deafening Essence of Fear"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Anger"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Fear"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Greed"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Hatred"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Sorrow"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Torment"] := 1
ITEMS_OF_INTEREST["Muttering Essence of Woe"] := 1
ITEMS_OF_INTEREST["Remnant of Corruption"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Dread"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Envy"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Greed"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Loathing"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Misery"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Rage"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Scorn"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Sorrow"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Spite"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Zeal"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Anger"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Envy"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Fear"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Hatred"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Loathing"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Misery"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Rage"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Scorn"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Sorrow"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Spite"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Woe"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Wrath"] := 1
ITEMS_OF_INTEREST["Shrieking Essence of Zeal"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Anger"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Anguish"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Doubt"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Fear"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Greed"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Hatred"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Loathing"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Rage"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Sorrow"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Spite"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Suffering"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Torment"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Woe"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Wrath"] := 1
ITEMS_OF_INTEREST["Wailing Essence of Zeal"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Anger"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Doubt"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Fear"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Greed"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Hatred"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Rage"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Sorrow"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Suffering"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Torment"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Woe"] := 1
ITEMS_OF_INTEREST["Weeping Essence of Wrath"] := 1
ITEMS_OF_INTEREST["Whispering Essence of Contempt"] := 1
ITEMS_OF_INTEREST["Whispering Essence of Greed"] := 1
ITEMS_OF_INTEREST["Whispering Essence of Hatred"] := 1
ITEMS_OF_INTEREST["Whispering Essence of Woe"] := 1
ITEMS_OF_INTEREST["Screaming Essence of Doubt"] := 0.84
ITEMS_OF_INTEREST["Screaming Essence of Wrath"] := 0.83
ITEMS_OF_INTEREST["Screaming Essence of Anguish"] := 0.82
ITEMS_OF_INTEREST["Screaming Essence of Hatred"] := 0.78
ITEMS_OF_INTEREST["Screaming Essence of Anger"] := 0.76
ITEMS_OF_INTEREST["Shrieking Essence of Torment"] := 0.55
ITEMS_OF_INTEREST["Screaming Essence of Fear"] := 0.53
ITEMS_OF_INTEREST["Shrieking Essence of Anguish"] := 0.53
ITEMS_OF_INTEREST["Deafening Essence of Anguish"] := 0.5
ITEMS_OF_INTEREST["Deafening Essence of Doubt"] := 0.5
ITEMS_OF_INTEREST["Deafening Essence of Misery"] := 0.5
ITEMS_OF_INTEREST["Deafening Essence of Suffering"] := 0.5
ITEMS_OF_INTEREST["Deafening Essence of Torment"] := 0.5
ITEMS_OF_INTEREST["Screaming Essence of Suffering"] := 0.5
ITEMS_OF_INTEREST["Screaming Essence of Torment"] := 0.5
ITEMS_OF_INTEREST["Screaming Essence of Woe"] := 0.5
ITEMS_OF_INTEREST["Shrieking Essence of Doubt"] := 0.5
ITEMS_OF_INTEREST["Shrieking Essence of Suffering"] := 0.5
ITEMS_OF_INTEREST["Awakened Enlighten Support"] := 5997.39
ITEMS_OF_INTEREST["Awakened Empower Support"] := 3630.2
ITEMS_OF_INTEREST["Awakened Greater Multiple Projectiles Support"] := 2359.63
ITEMS_OF_INTEREST["Awakened Multistrike Support"] := 2087.36
ITEMS_OF_INTEREST["Awakened Spell Echo Support"] := 1140.13
ITEMS_OF_INTEREST["Awakened Enhance Support"] := 1008.24
ITEMS_OF_INTEREST["Enlighten Support"] := 45
ITEMS_OF_INTEREST["Anomalous Enlighten Support"] := 363.02
ITEMS_OF_INTEREST["Awakened Elemental Damage with Attacks Support"] := 272.26
ITEMS_OF_INTEREST["Awakened Increased Area of Effect Support"] := 199.66
ITEMS_OF_INTEREST["Awakened Elemental Focus Support"] := 199.66
ITEMS_OF_INTEREST["Awakened Cast On Critical Strike Support"] := 181.78
ITEMS_OF_INTEREST["Awakened Fork Support"] := 181.51
ITEMS_OF_INTEREST["Elemental Penetration Support"] := 70
ITEMS_OF_INTEREST["Anomalous Empower Support"] := 78
ITEMS_OF_INTEREST["Awakened Burning Damage Support"] := 40
ITEMS_OF_INTEREST["Awakened Chain Support"] := 70
ITEMS_OF_INTEREST["Empower Support"] := 19
ITEMS_OF_INTEREST["Awakened Added Cold Damage Support"] := 15
ITEMS_OF_INTEREST["Awakened Controlled Destruction Support"] := 45
ITEMS_OF_INTEREST["Awakened Unbound Ailments Support"] := 45
ITEMS_OF_INTEREST["Awakened Added Lightning Damage Support"] := 40
ITEMS_OF_INTEREST["Awakened Fire Penetration Support"] := 40
ITEMS_OF_INTEREST["Awakened Minion Damage Support"] := 40
ITEMS_OF_INTEREST["Awakened Added Fire Damage Support"] := 40
ITEMS_OF_INTEREST["Awakened Brutality Support"] := 15
ITEMS_OF_INTEREST["Awakened Spell Cascade Support"] := 35
ITEMS_OF_INTEREST["Awakened Swift Affliction Support"] := 40
ITEMS_OF_INTEREST["Anomalous Flame Surge"] := 40
ITEMS_OF_INTEREST["Divergent Precision"] := 32.32
ITEMS_OF_INTEREST["Awakened Added Chaos Damage Support"] := 31.36
ITEMS_OF_INTEREST["Divergent Tornado Shot"] := 30
ITEMS_OF_INTEREST["Divergent Clarity"] := 30
ITEMS_OF_INTEREST["Awakened Void Manipulation Support"] := 29
ITEMS_OF_INTEREST["Anomalous Enhance Support"] := 24.21
ITEMS_OF_INTEREST["Awakened Unleash Support"] := 20
ITEMS_OF_INTEREST["Divergent Defiance Banner"] := 15
ITEMS_OF_INTEREST["Ritual Splinter"] := 0.0774